title: "The Portavoz Project"
description: "A digital archive of Spanish to English literary translations."
baseurl: "/portavoz-project"
url: "https://maxritterband.github.io"

collections:
  translations:
    output: true
    permalink: /translations/:year/:slug/

  translators:
    output: true
    permalink: /translators/:name/

markdown: kramdown
